---
language: ruby
env:
  - RUBYLIB=lib
  - RUBYLIB=
script: mspec spec
rvm:
  - 2.2
  - rbx-2
matrix:
  exclude:
    - rvm: 2.2
      env: RUBYLIB=lib
    - rvm: rbx-2
      env: RUBYLIB=
os:
  - linux
  - osx
sudo: false
